version: '3'
services:
    nginx:
        container_name: nginx
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"